[server]
runOnSave = true
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]
primaryColor = "#ff0000"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1f2937"
textColor = "#fafafa"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
magicEnabled = true
fastRerenderEnabled = true